import os
import json
import numpy as np
from redis import asyncio as aioredis
from sentence_transformers import SentenceTransformer
from app.services.metrics import cache_hits_total, cache_misses_total

# Initialize the embedding model (this downloads it locally the first time)
print("Loading embedding model...")
_model = None

def get_embedding_model():
    """Lazy loads the model only when it is actually needed"""
    global _model
    if _model is None:
        print("🧠 Downloading/Loading Embedding Model...")
        _model = SentenceTransformer('all-MiniLM-L6-v2')
    return _model

# Initialize the Redis connection
redis_url = os.getenv("REDIS_URL", "redis://localhost:6379/0")
redis_client = aioredis.from_url(redis_url)

def cosine_similarity(v1, v2):
    """Calculates the similarity between two vectors (0 to 1)."""
    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

async def check_semantic_cache(prompt: str, threshold: float = 0.92, prompt_version: str = "v1", tenant_id: str = "default"):
    """Embeds the prompt and checks Redis for a similar question."""
    model = get_embedding_model()
    prompt_embedding = model.encode(prompt)

    # Search for cached answers generated by the SAME prompt version!
    keys = await redis_client.keys(f'cache:{prompt_version}:*')

    for key in keys:
        cached_data = await redis_client.hgetall(key)
        if not cached_data:
            continue

        cached_embedding_bytes = cached_data[b'embedding']
        cached_embedding = np.frombuffer(cached_embedding_bytes, dtype=np.float32)
        similarity = cosine_similarity(prompt_embedding, cached_embedding)

        if similarity > threshold:
            print(f"✅ Cache HIT! Similarity: {similarity:.4f} (Version: {prompt_version})")
            cache_hits_total.labels(prompt_version=prompt_version, tenant_id=tenant_id).inc()
            return cached_data[b'response'].decode('utf-8')

    print(f"❌ Cache MISS (Version: {prompt_version})")
    cache_misses_total.labels(prompt_version=prompt_version, tenant_id=tenant_id).inc()
    return None

async def save_to_cache(prompt: str, response: str, prompt_version: str = "v1", ttl: int = 3600):
    """Saves a new prompt/response pair to Redis."""
    # Ensure the embedding model is loaded
    model = get_embedding_model()
    prompt_embedding = model.encode(prompt)
    
    import hashlib
    prompt_hash = hashlib.sha256(prompt.encode()).hexdigest()
    
    # Save the cache key with the prompt_version included
    key = f"cache:{prompt_version}:{prompt_hash}"
    
    await redis_client.hset(key, mapping={
        'embedding': prompt_embedding.tobytes(),
        'response': response
    })
    await redis_client.expire(key, ttl)
    print(f"💾 Saved to Redis Cache (Version: {prompt_version})")