from prometheus_client import Counter, Histogram, Gauge

# We define the labels required by the roadmap: prompt_version and tenant_id
_LABELS = ["prompt_version", "tenant_id"]

# 1. LLM Token Spend (Counter)
llm_token_spend_total = Counter(
    "llm_token_spend_total",
    "Total number of tokens generated by the LLM",
    _LABELS
)

# 2. LLM Request Latency (Histogram)
llm_request_latency_seconds = Histogram(
    "llm_request_latency_seconds",
    "Latency of LLM generation requests in seconds",
    _LABELS
)

# 3 & 4. Cache Efficiency (Counters)
cache_hits_total = Counter(
    "cache_hits_total",
    "Total semantic cache hits",
    _LABELS
)

cache_misses_total = Counter(
    "cache_misses_total",
    "Total semantic cache misses",
    _LABELS
)

# 5. Hallucination Score (Gauge - to be used in Phase 3)
hallucination_score = Gauge(
    "hallucination_score",
    "RAGAS faithfulness score from the evaluation suite",
    _LABELS
)