services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: ai_gateway
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - app

  app:
    build: .
    ports:
      - "8000:8000"
      - "50051:50051"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - REDIS_URL=redis://redis:6379/0
      # 👇 Give the app the connection string to talk to Postgres
      - DATABASE_URL=postgresql+asyncpg://admin:secretpassword@db:5432/ai_gateway
      - JWT_SECRET=super-secret-key-change-this-in-production-99887766
      - JWT_ALGORITHM=HS256
      - HF_HUB_DISABLE_HTTP2=1
    depends_on:
      - redis
      - db

  # 👇 MOVED UP: These are now properly under "services"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

# 👇 3. Define the persistent volume for the database at the VERY end
volumes:
  postgres_data:
