global:
  scrape_interval: 5s # Scrape data every 5 seconds for near real-time dashboards

scrape_configs:
  - job_name: "ai_gateway"
    metrics_path: "/metrics"
    # In Docker, 'app' is the name of your FastAPI container
    static_configs:
      - targets: ["app:8000"]
