global:
  scrape_interval: 5s # Scrape data every 5 seconds for near real-time dashboards

scrape_configs:
  - job_name: "fastapi-gateway"
    static_configs:
      # In Docker, 'app' is the name of your FastAPI container
      - targets: ["app:8000"]
